version: "2"

networks:
  mynetwork:
    external:
      name: web

services:
  twitoryback:
    image: twitory/back
    command: /go/bin/app -config=/app/config/config.yaml server
    volumes:
    - ./archive:/app/archive
    - .:/app/config
    networks:
      default: {}
      mynetwork:
        aliases:
        - tb
  twitoryfront:
    image: twitory/front
    command: "gunicorn frontend.front:app -b 0.0.0.0:80"
    volumes:
    - ./archive:/app/archive
    - .:/app
    networks:
      default: {}
      mynetwork:
        aliases:
          - tf